package Prueba;

/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CorcheteIzquierdo = 1;
  /** RegularExpression Id. */
  int CorcheteDerecho = 2;
  /** RegularExpression Id. */
  int ParentesisIzquierdo = 3;
  /** RegularExpression Id. */
  int ParentesisDerecho = 4;
  /** RegularExpression Id. */
  int LlaveIzquierda = 5;
  /** RegularExpression Id. */
  int LlaveDerecha = 6;
  /** RegularExpression Id. */
  int PuntoComa = 7;
  /** RegularExpression Id. */
  int Clase = 8;
  /** RegularExpression Id. */
  int Publico = 9;
  /** RegularExpression Id. */
  int Regresar = 10;
  /** RegularExpression Id. */
  int Entero = 11;
  /** RegularExpression Id. */
  int Booleano = 12;
  /** RegularExpression Id. */
  int Void = 13;
  /** RegularExpression Id. */
  int Si = 14;
  /** RegularExpression Id. */
  int Entonces = 15;
  /** RegularExpression Id. */
  int Mientras = 16;
  /** RegularExpression Id. */
  int Imprimir = 17;
  /** RegularExpression Id. */
  int Asignacion = 18;
  /** RegularExpression Id. */
  int Y = 19;
  /** RegularExpression Id. */
  int MenorQue = 20;
  /** RegularExpression Id. */
  int MenorIgualQue = 21;
  /** RegularExpression Id. */
  int MayorIgualQue = 22;
  /** RegularExpression Id. */
  int Diferente = 23;
  /** RegularExpression Id. */
  int Igual = 24;
  /** RegularExpression Id. */
  int Suma = 25;
  /** RegularExpression Id. */
  int Resta = 26;
  /** RegularExpression Id. */
  int Multiplicacion = 27;
  /** RegularExpression Id. */
  int Coma = 28;
  /** RegularExpression Id. */
  int Punto = 29;
  /** RegularExpression Id. */
  int Longitud = 30;
  /** RegularExpression Id. */
  int Numero = 31;
  /** RegularExpression Id. */
  int Verdadero = 32;
  /** RegularExpression Id. */
  int Falso = 33;
  /** RegularExpression Id. */
  int Este = 34;
  /** RegularExpression Id. */
  int Nuevo = 35;
  /** RegularExpression Id. */
  int Negacion = 36;
  /** RegularExpression Id. */
  int Identificador = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"class\"",
    "\"public\"",
    "\"return\"",
    "\"int\"",
    "\"boolean\"",
    "\"void\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"System.out.println\"",
    "\"=\"",
    "\"&&\"",
    "\"<\"",
    "\"<=\"",
    "\" >=\"",
    "\"!=\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\",\"",
    "\".\"",
    "\"length\"",
    "<Numero>",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"!\"",
    "<Identificador>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"//\"",
    "\"/*\"",
    "\"*/\"",
  };

}
